version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8003:8003"
    volumes:
      - /web_dados
      - ./src/:/web_dados/src/:ro
    environment:
      - NODE_ENV=production
      - GATSBY_WEBPACK_PUBLICPATH=/web_dados
