version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8003:8003"
    volumes:
      - /web_dados/node_modules
      - .:/web_dados
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/