name: CI

on:
  push:
    branches: [ ricardo/githubpages ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: npm install

      - name: Deploy 🚀
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths


  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: Install Packages
        run: npm install
      - name: Run ESLint
        run: npx eslint
